VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "ThisWorkbook"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = True
Attribute VB_Exposed = True
'Private Sub Workbook_Open()
'MsgBox "REMINDER - This file is used by multiple associates on a regular basis." _
& Chr(13) & Chr(10) & Chr(13) & Chr(10) _
& "Please do not keep it open any longer than necessary and EXIT as soon as possible.", vbExclamation
'End Sub
