VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "Sheet3"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = True
Attribute VB_Exposed = True
Private Sub CommandButton1_Click()
ActiveWorkbook.FollowHyperlink _
Address:="https://navistarinc.sharepoint.com/teams/NavPG/PTAB/_layouts/15/listform.aspx?PageType=8&ListId=%7B8581A6BE-9C78-40CF-960C-0AF9BCCADE8B%7D&RootFolder=%2Fteams%2FNavPG%2FPTAB%2FLists%2FDriverSignOff&Source=https%3A%2F%2Fnavistarinc.sharepoint.com%2Fteams%2FNavPG%2FPTAB%2FLists%2FDriverSignOff%2FAllItems.aspx&ContentTypeId=0x0100111F2F745E50CA4199D7F25F5D92A5AA"
End Sub

